2021-07-19 09:44:13,461 [sky_gitlab_robot]: <ERROR> {'id': 4154, 'iid': 823, 'project_id': 45, 'title': '请帮忙分析下下面这个双机问题', 'description': '## 问题来源\n\n* 客户: \n* 联系人: sheng.chunming1\n* 联系方式: sheng.chunming1@zte.com.cn\n* 邮件日期：\n\n@miaopengcheng @hblinux007 @xuyunfeng \n\n## 问题描述\n\n## 分析\n\n## 建议', 'state': 'opened', 'created_at': '2021-07-13T14:01:29.763+08:00', 'updated_at': '2021-07-13T14:06:43.915+08:00', 'closed_at': None, 'closed_by': None, 'labels': ['Done', 'os:filesystem_no_space', '客户：中兴'], 'milestone': None, 'assignees': [], 'author': {'id': 14, 'name': 'yangyingfa', 'username': 'yangyingfa', 'state': 'active', 'avatar_url': 'https://gitlab.skybilityha.com/uploads/-/system/user/avatar/14/avatar.png', 'web_url': 'https://gitlab.skybilityha.com/yangyingfa'}, 'assignee': None, 'user_notes_count': 1, 'merge_requests_count': 0, 'upvotes': 0, 'downvotes': 0, 'due_date': None, 'confidential': False, 'discussion_locked': None, 'web_url': 'https://gitlab.skybilityha.com/support/HA2.8/-/issues/823', 'time_stats': {'time_estimate': 0, 'total_time_spent': 0, 'human_time_estimate': None, 'human_total_time_spent': None}, 'task_completion_status': {'count': 0, 'completed_count': 0}, 'has_tasks': False, '_links': {'self': 'https://gitlab.skybilityha.com/api/v4/projects/45/issues/823', 'notes': 'https://gitlab.skybilityha.com/api/v4/projects/45/issues/823/notes', 'award_emoji': 'https://gitlab.skybilityha.com/api/v4/projects/45/issues/823/award_emoji', 'project': 'https://gitlab.skybilityha.com/api/v4/projects/45'}, 'references': {'short': '#823', 'relative': '#823', 'full': 'support/HA2.8#823'}, 'moved_to_id': None} [DataCollect.py:48:do_collect]
2021-07-19 09:44:13,555 [sky_gitlab_robot]: <ERROR> {'id': 4105, 'iid': 818, 'project_id': 45, 'title': '配置问题', 'description': '## 问题来源\n\n* 客户: zte\n* 联系人: \n* 联系方式:  peng.tao7@zte.com.cn\n* 邮件日期：\n\n@miaopengcheng @hblinux007 @xuyunfeng \n\n## 问题描述\n\n## 分析\n\n## 建议', 'state': 'opened', 'created_at': '2021-06-28T10:08:57.957+08:00', 'updated_at': '2021-07-08T16:47:59.850+08:00', 'closed_at': None, 'closed_by': None, 'labels': ['Done', '客户：中兴'], 'milestone': None, 'assignees': [{'id': 54, 'name': 'Jiyingyu', 'username': 'yingyu', 'state': 'active', 'avatar_url': 'https://secure.gravatar.com/avatar/615bf89ea19b7fb1e905d03a74c2c1e6?s=80&d=identicon', 'web_url': 'https://gitlab.skybilityha.com/yingyu'}], 'author': {'id': 14, 'name': 'yangyingfa', 'username': 'yangyingfa', 'state': 'active', 'avatar_url': 'https://gitlab.skybilityha.com/uploads/-/system/user/avatar/14/avatar.png', 'web_url': 'https://gitlab.skybilityha.com/yangyingfa'}, 'assignee': {'id': 54, 'name': 'Jiyingyu', 'username': 'yingyu', 'state': 'active', 'avatar_url': 'https://secure.gravatar.com/avatar/615bf89ea19b7fb1e905d03a74c2c1e6?s=80&d=identicon', 'web_url': 'https://gitlab.skybilityha.com/yingyu'}, 'user_notes_count': 1, 'merge_requests_count': 0, 'upvotes': 0, 'downvotes': 0, 'due_date': None, 'confidential': False, 'discussion_locked': None, 'web_url': 'https://gitlab.skybilityha.com/support/HA2.8/-/issues/818', 'time_stats': {'time_estimate': 0, 'total_time_spent': 0, 'human_time_estimate': None, 'human_total_time_spent': None}, 'task_completion_status': {'count': 0, 'completed_count': 0}, 'has_tasks': False, '_links': {'self': 'https://gitlab.skybilityha.com/api/v4/projects/45/issues/818', 'notes': 'https://gitlab.skybilityha.com/api/v4/projects/45/issues/818/notes', 'award_emoji': 'https://gitlab.skybilityha.com/api/v4/projects/45/issues/818/award_emoji', 'project': 'https://gitlab.skybilityha.com/api/v4/projects/45'}, 'references': {'short': '#818', 'relative': '#818', 'full': 'support/HA2.8#818'}, 'moved_to_id': None} [DataCollect.py:48:do_collect]
2021-07-19 09:44:13,647 [sky_gitlab_robot]: <ERROR> {'id': 4101, 'iid': 817, 'project_id': 45, 'title': '单次紧急故障】OA20210625720600山西移动多套U31-EMS ZDC经常运行期间自动挂掉，手动可正常恢复，运行一段时间故障复现', 'description': '## 问题来源\n\n* 客户: 中兴\n* 联系人: \n* 联系方式: guo.jin91@zte.com.cn\n* 邮件日期：\n\n\n\n## 问题描述\n\n## 分析\n\n## 建议', 'state': 'opened', 'created_at': '2021-06-25T18:02:52.602+08:00', 'updated_at': '2021-06-29T17:43:34.765+08:00', 'closed_at': None, 'closed_by': None, 'labels': ['Done', 'os:lack_of_memory', 'report_need', '客户：中兴'], 'milestone': None, 'assignees': [], 'author': {'id': 14, 'name': 'yangyingfa', 'username': 'yangyingfa', 'state': 'active', 'avatar_url': 'https://gitlab.skybilityha.com/uploads/-/system/user/avatar/14/avatar.png', 'web_url': 'https://gitlab.skybilityha.com/yangyingfa'}, 'assignee': None, 'user_notes_count': 3, 'merge_requests_count': 0, 'upvotes': 0, 'downvotes': 0, 'due_date': None, 'confidential': False, 'discussion_locked': None, 'web_url': 'https://gitlab.skybilityha.com/support/HA2.8/-/issues/817', 'time_stats': {'time_estimate': 0, 'total_time_spent': 0, 'human_time_estimate': None, 'human_total_time_spent': None}, 'task_completion_status': {'count': 0, 'completed_count': 0}, 'has_tasks': False, '_links': {'self': 'https://gitlab.skybilityha.com/api/v4/projects/45/issues/817', 'notes': 'https://gitlab.skybilityha.com/api/v4/projects/45/issues/817/notes', 'award_emoji': 'https://gitlab.skybilityha.com/api/v4/projects/45/issues/817/award_emoji', 'project': 'https://gitlab.skybilityha.com/api/v4/projects/45'}, 'references': {'short': '#817', 'relative': '#817', 'full': 'support/HA2.8#817'}, 'moved_to_id': None} [DataCollect.py:48:do_collect]
2021-07-19 09:44:13,749 [sky_gitlab_robot]: <ERROR> {'id': 4039, 'iid': 813, 'project_id': 45, 'title': '浙江嘉兴NDS服务器当前因故障停止服务，无法启动，也无法切到备机上，烦请支撑，感谢。还是之前遇到的那台相同服务器NDS-L4,10.212.120.196', 'description': '## 问题来源\n\n* 客户: 中兴\n* 联系人: 李闯\n* 联系方式: li.chuang2@zte.com.cn\n* 邮件日期：日期\n\n@yangyingfa  @hblinux007 @miaopengcheng  \n\n## 问题描述\n如下，NDS-L4服务器，现场试过reset，没有效果，按照之前提供的处理脑裂的方法处理，短暂恢复后，又出现下图中一样的情况，麻烦帮忙支撑，感谢。\n\n附件是服务器的dld文件和备机的hacollect日志，NDS-L4的日志有300M，暂无法通过邮件发送，麻烦帮忙提供对应的服务器，感谢。  \n[halog-NDS-L4-20210608154105.7z](/uploads/48e77bccf0532600cd19bd53268c7f20/halog-NDS-L4-20210608154105.7z)  \n[halog-standby-1-20210608154221.tar.gz](/uploads/0d379f60cdfd1447e6003e51ff844435/halog-standby-1-20210608154221.tar.gz)  \n[halog-NDS-L3-20210608211828.tar.gz](/uploads/0534c13cebeb97632d8f041f22c94563/halog-NDS-L3-20210608211828.tar.gz)  \n![image](/uploads/6a493c910dfbd417c7be01aac8b4398c/image.png)  \n## 分析\n\n## 建议', 'state': 'opened', 'created_at': '2021-06-08T18:32:37.861+08:00', 'updated_at': '2021-06-16T16:12:37.346+08:00', 'closed_at': None, 'closed_by': None, 'labels': ['Done', '客户：中兴'], 'milestone': None, 'assignees': [], 'author': {'id': 48, 'name': '缪鹏程', 'username': 'miaopengcheng', 'state': 'active', 'avatar_url': 'https://secure.gravatar.com/avatar/b81be22b329a52c083dcb2ce610f312d?s=80&d=identicon', 'web_url': 'https://gitlab.skybilityha.com/miaopengcheng'}, 'assignee': None, 'user_notes_count': 9, 'merge_requests_count': 0, 'upvotes': 0, 'downvotes': 0, 'due_date': None, 'confidential': False, 'discussion_locked': None, 'web_url': 'https://gitlab.skybilityha.com/support/HA2.8/-/issues/813', 'time_stats': {'time_estimate': 0, 'total_time_spent': 0, 'human_time_estimate': None, 'human_total_time_spent': None}, 'task_completion_status': {'count': 0, 'completed_count': 0}, 'has_tasks': False, '_links': {'self': 'https://gitlab.skybilityha.com/api/v4/projects/45/issues/813', 'notes': 'https://gitlab.skybilityha.com/api/v4/projects/45/issues/813/notes', 'award_emoji': 'https://gitlab.skybilityha.com/api/v4/projects/45/issues/813/award_emoji', 'project': 'https://gitlab.skybilityha.com/api/v4/projects/45'}, 'references': {'short': '#813', 'relative': '#813', 'full': 'support/HA2.8#813'}, 'moved_to_id': None} [DataCollect.py:48:do_collect]
2021-07-19 09:44:13,874 [sky_gitlab_robot]: <ERROR> {'id': 4023, 'iid': 812, 'project_id': 45, 'title': '请帮忙分析下，为什么会出现zdc7节点的错误，感谢', 'description': '## 问题来源\n\n* 客户: 中兴\n* 联系人: 盛春明\n* 联系方式: sheng.chunming1@zte.com.cn\n* 邮件日期：2021年5月25日\n\n@hblinux007 @yangyingfa @miaopengcheng  \n\n## 问题描述\n![image](/uploads/303af32c689f02bec0769b168cd7d47b/image.png)  \n[halog-zdc7-20210525113839.tar.gz](/uploads/0aa9031217ef8da4a96ead3cdd02f44c/halog-zdc7-20210525113839.tar.gz)  \n## 分析\n\n## 建议', 'state': 'opened', 'created_at': '2021-05-25T12:06:43.853+08:00', 'updated_at': '2021-06-01T15:53:14.015+08:00', 'closed_at': None, 'closed_by': None, 'labels': ['Done', '客户：中兴'], 'milestone': None, 'assignees': [], 'author': {'id': 48, 'name': '缪鹏程', 'username': 'miaopengcheng', 'state': 'active', 'avatar_url': 'https://secure.gravatar.com/avatar/b81be22b329a52c083dcb2ce610f312d?s=80&d=identicon', 'web_url': 'https://gitlab.skybilityha.com/miaopengcheng'}, 'assignee': None, 'user_notes_count': 1, 'merge_requests_count': 0, 'upvotes': 0, 'downvotes': 0, 'due_date': None, 'confidential': False, 'discussion_locked': None, 'web_url': 'https://gitlab.skybilityha.com/support/HA2.8/-/issues/812', 'time_stats': {'time_estimate': 0, 'total_time_spent': 0, 'human_time_estimate': None, 'human_total_time_spent': None}, 'task_completion_status': {'count': 0, 'completed_count': 0}, 'has_tasks': False, '_links': {'self': 'https://gitlab.skybilityha.com/api/v4/projects/45/issues/812', 'notes': 'https://gitlab.skybilityha.com/api/v4/projects/45/issues/812/notes', 'award_emoji': 'https://gitlab.skybilityha.com/api/v4/projects/45/issues/812/award_emoji', 'project': 'https://gitlab.skybilityha.com/api/v4/projects/45'}, 'references': {'short': '#812', 'relative': '#812', 'full': 'support/HA2.8#812'}, 'moved_to_id': None} [DataCollect.py:48:do_collect]
2021-07-19 09:44:13,951 [sky_gitlab_robot]: <ERROR> {'id': 4022, 'iid': 811, 'project_id': 45, 'title': '您好，河北移动网管服务器skybility出现脑裂，日志已提取，请分析定位，谢谢', 'description': '## 问题来源\n\n* 客户: zte\n* 联系人: \n* 联系方式: jin.zhe@zte.com.cn\n* 邮件日期：\n\n@miaopengcheng @hblinux007 @xuyunfeng \n\n## 问题描述\n[halog-standby1-20210519165911.tar.7z](/uploads/6eb8f0037ee1d86398e78857ecf028b6/halog-standby1-20210519165911.tar.7z)\n\n[halog-zdc6-20210519165610.tar.7z](/uploads/664de7a74a12c2f8f988ffb989228af0/halog-zdc6-20210519165610.tar.7z)\n\n[halog-zdc4-20210519165407.tar.7z](/uploads/6e1675e429a70c880ac57f8473db7411/halog-zdc4-20210519165407.tar.7z)\n\n[halog-ems1-20210519165029.tar.gz](/uploads/4c151fc2d50ffb9845193be738d22be5/halog-ems1-20210519165029.tar.gz)\n## 分析\n\n## 建议', 'state': 'opened', 'created_at': '2021-05-24T09:41:04.887+08:00', 'updated_at': '2021-05-31T14:54:58.609+08:00', 'closed_at': None, 'closed_by': None, 'labels': ['Done', 'ha:node-split', '客户：中兴'], 'milestone': None, 'assignees': [], 'author': {'id': 14, 'name': 'yangyingfa', 'username': 'yangyingfa', 'state': 'active', 'avatar_url': 'https://gitlab.skybilityha.com/uploads/-/system/user/avatar/14/avatar.png', 'web_url': 'https://gitlab.skybilityha.com/yangyingfa'}, 'assignee': None, 'user_notes_count': 1, 'merge_requests_count': 0, 'upvotes': 0, 'downvotes': 0, 'due_date': None, 'confidential': False, 'discussion_locked': None, 'web_url': 'https://gitlab.skybilityha.com/support/HA2.8/-/issues/811', 'time_stats': {'time_estimate': 0, 'total_time_spent': 0, 'human_time_estimate': None, 'human_total_time_spent': None}, 'task_completion_status': {'count': 0, 'completed_count': 0}, 'has_tasks': False, '_links': {'self': 'https://gitlab.skybilityha.com/api/v4/projects/45/issues/811', 'notes': 'https://gitlab.skybilityha.com/api/v4/projects/45/issues/811/notes', 'award_emoji': 'https://gitlab.skybilityha.com/api/v4/projects/45/issues/811/award_emoji', 'project': 'https://gitlab.skybilityha.com/api/v4/projects/45'}, 'references': {'short': '#811', 'relative': '#811', 'full': 'support/HA2.8#811'}, 'moved_to_id': None} [DataCollect.py:48:do_collect]
2021-07-19 09:44:14,045 [sky_gitlab_robot]: <ERROR> {'id': 4017, 'iid': 809, 'project_id': 45, 'title': 'skybility双机资源报错，双机软件没有正常切换，需分析原因', 'description': '## 问题来源\n\n* 客户: 中兴\n* 联系人: 李闯\n* 联系方式: li.chuang2@zte.com.cn\n* 邮件日期：2021年5月20日\n\n@hblinux007 @yangyingfa @miaopengcheng \n\n## 问题描述\nskybility双机资源报错，双机软件没有正常切换，需分析原因，申请傲冠进行远程单次服务诊断  \n同意，请安排技术人员进行支持，支持完成后提供下技术服务报告，用来完成单次采购合同发起，谢谢！  \n双机里面，EMSslave报错，无法在备机上启动，5月18日已通过重置错误，重新启动回来。  \n![image](/uploads/819c0eb2b6f8b90f5508261e92d099de/image.png)  \n\n## 分析\n\n## 建议', 'state': 'opened', 'created_at': '2021-05-20T15:55:54.035+08:00', 'updated_at': '2021-06-29T17:22:27.062+08:00', 'closed_at': None, 'closed_by': None, 'labels': ['Done', 'cause_by:application', '客户：中兴'], 'milestone': None, 'assignees': [], 'author': {'id': 48, 'name': '缪鹏程', 'username': 'miaopengcheng', 'state': 'active', 'avatar_url': 'https://secure.gravatar.com/avatar/b81be22b329a52c083dcb2ce610f312d?s=80&d=identicon', 'web_url': 'https://gitlab.skybilityha.com/miaopengcheng'}, 'assignee': None, 'user_notes_count': 3, 'merge_requests_count': 0, 'upvotes': 0, 'downvotes': 0, 'due_date': None, 'confidential': False, 'discussion_locked': None, 'web_url': 'https://gitlab.skybilityha.com/support/HA2.8/-/issues/809', 'time_stats': {'time_estimate': 0, 'total_time_spent': 0, 'human_time_estimate': None, 'human_total_time_spent': None}, 'task_completion_status': {'count': 0, 'completed_count': 0}, 'has_tasks': False, '_links': {'self': 'https://gitlab.skybilityha.com/api/v4/projects/45/issues/809', 'notes': 'https://gitlab.skybilityha.com/api/v4/projects/45/issues/809/notes', 'award_emoji': 'https://gitlab.skybilityha.com/api/v4/projects/45/issues/809/award_emoji', 'project': 'https://gitlab.skybilityha.com/api/v4/projects/45'}, 'references': {'short': '#809', 'relative': '#809', 'full': 'support/HA2.8#809'}, 'moved_to_id': None} [DataCollect.py:48:do_collect]
2021-07-19 09:44:14,211 [sky_gitlab_robot]: <ERROR> {'id': 4011, 'iid': 805, 'project_id': 45, 'title': '浙江嘉兴NDS服务器当前因故障切到备机上，暂时无法切回，麻烦帮忙提供支撑，感谢！', 'description': '## 问题来源\n\n* 客户: 中兴\n* 联系人: 李闯\n* 联系方式: li.chuang2@zte.com.cn\n* 邮件日期：2021年5月15日\n\n@hblinux007 @yangyingfa  @miaopengcheng \n\n## 问题描述\n```\n各位同事，您好，\n当前浙江嘉兴NDS-L4服务器在备机上，下发在主机启用的命令后没有反应，CRT登录到主机地址172.31.15.75上看磁盘空间如下：\n麻烦帮忙协助处理，当前在备机上无法切回。\n使用hacollect命令，取得备机日志如附件，取的主机日志220M，暂无法通过邮箱发送，看是否提供服务器或发送渠道，感谢！\n```\n[halog-standby-1-20210515163547.tar.gz](/uploads/be1da6536aec9c5e663fa7ff61bdb21f/halog-standby-1-20210515163547.tar.gz)  \n![image](/uploads/41b48fe45bf36344f09b60be5c600222/image.png)  \n![image](/uploads/a653f456f2d694f5c80ba48f9de8a992/image.png)  \n\n## 分析\n\n## 建议', 'state': 'opened', 'created_at': '2021-05-15T17:18:30.036+08:00', 'updated_at': '2021-05-21T10:21:19.990+08:00', 'closed_at': None, 'closed_by': None, 'labels': ['Done', '客户：中兴'], 'milestone': None, 'assignees': [], 'author': {'id': 48, 'name': '缪鹏程', 'username': 'miaopengcheng', 'state': 'active', 'avatar_url': 'https://secure.gravatar.com/avatar/b81be22b329a52c083dcb2ce610f312d?s=80&d=identicon', 'web_url': 'https://gitlab.skybilityha.com/miaopengcheng'}, 'assignee': None, 'user_notes_count': 15, 'merge_requests_count': 0, 'upvotes': 0, 'downvotes': 0, 'due_date': None, 'confidential': False, 'discussion_locked': None, 'web_url': 'https://gitlab.skybilityha.com/support/HA2.8/-/issues/805', 'time_stats': {'time_estimate': 0, 'total_time_spent': 0, 'human_time_estimate': None, 'human_total_time_spent': None}, 'task_completion_status': {'count': 0, 'completed_count': 0}, 'has_tasks': False, '_links': {'self': 'https://gitlab.skybilityha.com/api/v4/projects/45/issues/805', 'notes': 'https://gitlab.skybilityha.com/api/v4/projects/45/issues/805/notes', 'award_emoji': 'https://gitlab.skybilityha.com/api/v4/projects/45/issues/805/award_emoji', 'project': 'https://gitlab.skybilityha.com/api/v4/projects/45'}, 'references': {'short': '#805', 'relative': '#805', 'full': 'support/HA2.8#805'}, 'moved_to_id': None} [DataCollect.py:48:do_collect]
2021-07-19 09:44:14,385 [sky_gitlab_robot]: <ERROR> {'id': 3968, 'iid': 796, 'project_id': 45, 'title': '河北移动2套U31网管因为华为9312交换机倒换导致网管双机状态异常，--> OA20210419186100 skybility问题，已升级单次服务，请现场联系外包主管黄梦牙处理，请李总尽快指派，谢谢！', 'description': '## 问题来源\n\n* 客户: zte\n* 联系人: jin.zhe@zte.com.cn\n* 联系方式: jin.zhe@zte.com.cn\n* 邮件日期：\n\n@miaopengcheng @hblinux007 @xuyunfeng \n\n## 问题描述\n故障描述：\n\n    15日晚23时多，服务器上级交换机做主备倒换，我方服务器所在的网段(10.216.31.*、10.216.28.*)所有IP无法通信。传输恢复业务后，skybility上显示多个节点业务异常被切换至备机，部分节点切换出错自动停止了业务。\n\n    手动重置节点、启动节点业务没有任何反应。怀疑SKYBILITY发生脑裂，随后手动停止、启动所有节点的HA，重启后可以正常重置、启动和停止。\n\n然后逐个将业务手动在主节点启动后恢复。\n\n问题1：烦请看看日志，定位下当晚具体发生的什么问题，什么原因导致，有无解决或规避方案。\n\n   \n\n    在重启了HA后手动切换节点业务时发现，10.216.28.38OMMB集群，saahost4上的saa10、11、12在备机(saastd)运行，切换主节点(saahost4)时saa12的saa12_oracle_fs服务会在主节点上报错，报错信息见附件截图。两个节点的hacollect集群日志请见附件。\n\n\n\n问题2：该节点服务切换主节点时失败的原因。\n## 分析\n[halog-saastd1-20210416T022704.tar.gz](/uploads/015e778af7f4ed1aac5f90e1a03ed056/halog-saastd1-20210416T022704.tar.gz)\n\n[halog-saahost4-20210416T022622.tar.gz](/uploads/9461fc7b9f09c7b8c284fd4a355bb661/halog-saahost4-20210416T022622.tar.gz)\n## 建议', 'state': 'opened', 'created_at': '2021-04-20T09:19:09.029+08:00', 'updated_at': '2021-05-12T14:20:40.444+08:00', 'closed_at': None, 'closed_by': None, 'labels': ['Done', 'cause_by:network', '客户：中兴'], 'milestone': None, 'assignees': [], 'author': {'id': 14, 'name': 'yangyingfa', 'username': 'yangyingfa', 'state': 'active', 'avatar_url': 'https://gitlab.skybilityha.com/uploads/-/system/user/avatar/14/avatar.png', 'web_url': 'https://gitlab.skybilityha.com/yangyingfa'}, 'assignee': None, 'user_notes_count': 3, 'merge_requests_count': 0, 'upvotes': 0, 'downvotes': 0, 'due_date': None, 'confidential': False, 'discussion_locked': None, 'web_url': 'https://gitlab.skybilityha.com/support/HA2.8/-/issues/796', 'time_stats': {'time_estimate': 0, 'total_time_spent': 0, 'human_time_estimate': None, 'human_total_time_spent': None}, 'task_completion_status': {'count': 0, 'completed_count': 0}, 'has_tasks': False, '_links': {'self': 'https://gitlab.skybilityha.com/api/v4/projects/45/issues/796', 'notes': 'https://gitlab.skybilityha.com/api/v4/projects/45/issues/796/notes', 'award_emoji': 'https://gitlab.skybilityha.com/api/v4/projects/45/issues/796/award_emoji', 'project': 'https://gitlab.skybilityha.com/api/v4/projects/45'}, 'references': {'short': '#796', 'relative': '#796', 'full': 'support/HA2.8#796'}, 'moved_to_id': None} [DataCollect.py:48:do_collect]
2021-07-19 09:44:14,511 [sky_gitlab_robot]: <ERROR> {'id': 3958, 'iid': 793, 'project_id': 45, 'title': 'skybility协助印尼金光项目微波网管故障排查', 'description': '## 问题来源\n\n* 客户: zte\n* 联系人: ewan.liuyuewei@gmail.com\n* 联系方式: \n* 邮件日期：\n\n@jamesl @hblinux007 @fangjinzhen @husongtao\n\n## 问题描述\n[halog-OMC1-20210413T172740.tar.gz](/uploads/8a7e74c982b54c6423aa9d0c1bf9728b/halog-OMC1-20210413T172740.tar.gz)\n\n[halog-OMC2-20210413T173141.tar.gz](/uploads/2e0bbad23857dc7fd45513e408ed3801/halog-OMC2-20210413T173141.tar.gz)\n## 分析\n\n## 建议', 'state': 'opened', 'created_at': '2021-04-13T21:36:50.717+08:00', 'updated_at': '2021-04-19T14:48:08.638+08:00', 'closed_at': None, 'closed_by': None, 'labels': ['Done', '客户：中兴'], 'milestone': None, 'assignees': [], 'author': {'id': 14, 'name': 'yangyingfa', 'username': 'yangyingfa', 'state': 'active', 'avatar_url': 'https://gitlab.skybilityha.com/uploads/-/system/user/avatar/14/avatar.png', 'web_url': 'https://gitlab.skybilityha.com/yangyingfa'}, 'assignee': None, 'user_notes_count': 4, 'merge_requests_count': 0, 'upvotes': 0, 'downvotes': 0, 'due_date': None, 'confidential': False, 'discussion_locked': None, 'web_url': 'https://gitlab.skybilityha.com/support/HA2.8/-/issues/793', 'time_stats': {'time_estimate': 0, 'total_time_spent': 0, 'human_time_estimate': None, 'human_total_time_spent': None}, 'task_completion_status': {'count': 0, 'completed_count': 0}, 'has_tasks': False, '_links': {'self': 'https://gitlab.skybilityha.com/api/v4/projects/45/issues/793', 'notes': 'https://gitlab.skybilityha.com/api/v4/projects/45/issues/793/notes', 'award_emoji': 'https://gitlab.skybilityha.com/api/v4/projects/45/issues/793/award_emoji', 'project': 'https://gitlab.skybilityha.com/api/v4/projects/45'}, 'references': {'short': '#793', 'relative': '#793', 'full': 'support/HA2.8#793'}, 'moved_to_id': None} [DataCollect.py:48:do_collect]
2021-07-19 09:44:14,669 [sky_gitlab_robot]: <ERROR> {'id': 3953, 'iid': 789, 'project_id': 45, 'title': '4月4日或4月5日，中兴广西移动一套使用skybility双机软件的刀片网管有两个刀片节点双机挂死', 'description': '## 问题来源\n\n* 客户: 中兴\n* 联系人: 余泽兵\n* 联系方式: yu.zebin@zte.com.cn T: +86 7715595666 \n* 邮件日期：2021年4月9日\n\n@yangyingfa  @hblinux007 @fangjinzhen @husongtao\n\n## 问题描述\n4月4日或4月5日，中兴广西移动一套使用skybility双机软件的刀片网管有两个刀片节点双机挂死（看到两个刀片的skybility软件都是红色心跳线），后登录两刀片维护地址重启hacmm后恢复，请傲冠帮看附件收集的两刀片双机日志，给出这两个刀片发生skybility双机资源挂死的原因，移动用户需要知悉原因。  \n \n余泽兵  \n网优工程师  \n南宁处/第二片区/第三营销事业部  \n中兴通讯股份有限公司\n广西南宁市青秀区东葛路118号青秀万达广场西1栋1901, 邮编: 530022  \nT: +86 7715595666     M: +86 13407710258  \nE: yu.zebin@zte.com.cn  \nwww.zte.com.cn  \n\n[halog-ems2-20210408T132705.tar.gz](/uploads/23bd63eb5f496b428fae6db3d8f3b31f/halog-ems2-20210408T132705.tar.gz)  \n[halog-icm-20210408T132804.tar.gz](/uploads/8dbcadf8f748b2e97ecedaeb951ff186/halog-icm-20210408T132804.tar.gz)  \n\n## 分析\n\n## 建议', 'state': 'opened', 'created_at': '2021-04-09T17:04:31.512+08:00', 'updated_at': '2021-04-15T11:24:43.306+08:00', 'closed_at': None, 'closed_by': None, 'labels': ['Done', '客户：中兴'], 'milestone': None, 'assignees': [], 'author': {'id': 48, 'name': '缪鹏程', 'username': 'miaopengcheng', 'state': 'active', 'avatar_url': 'https://secure.gravatar.com/avatar/b81be22b329a52c083dcb2ce610f312d?s=80&d=identicon', 'web_url': 'https://gitlab.skybilityha.com/miaopengcheng'}, 'assignee': None, 'user_notes_count': 2, 'merge_requests_count': 0, 'upvotes': 0, 'downvotes': 0, 'due_date': None, 'confidential': False, 'discussion_locked': None, 'web_url': 'https://gitlab.skybilityha.com/support/HA2.8/-/issues/789', 'time_stats': {'time_estimate': 0, 'total_time_spent': 0, 'human_time_estimate': None, 'human_total_time_spent': None}, 'task_completion_status': {'count': 0, 'completed_count': 0}, 'has_tasks': False, '_links': {'self': 'https://gitlab.skybilityha.com/api/v4/projects/45/issues/789', 'notes': 'https://gitlab.skybilityha.com/api/v4/projects/45/issues/789/notes', 'award_emoji': 'https://gitlab.skybilityha.com/api/v4/projects/45/issues/789/award_emoji', 'project': 'https://gitlab.skybilityha.com/api/v4/projects/45'}, 'references': {'short': '#789', 'relative': '#789', 'full': 'support/HA2.8#789'}, 'moved_to_id': None} [DataCollect.py:48:do_collect]
2021-07-19 09:44:14,670 [sky_gitlab_robot]: <WARNING> Failed to parse description, issue is 789, with repo Ha28,details: 'NoneType' object is not subscriptable [DataCollect.py:95:_get_customer_from_description]
2021-07-19 09:44:14,750 [sky_gitlab_robot]: <ERROR> {'id': 3940, 'iid': 787, 'project_id': 45, 'title': '中兴新疆客户申请将测试license替换为正式license', 'description': '## 问题来源\n\n* 客户: 中兴\n* 联系人: 陈文海\n* 联系方式: 13669967820@163.com\n* 邮件日期：2021年4月7日\n\n@yangyingfa  @hblinux007 @fangjinzhen @husongtao\n\n## 问题描述\n你好！\n按照你的方法，还是只能申请测试License，无法更换为正式license，没有注册号，请问注册号怎么填写？？？  \n![image](/uploads/0dc0e04d7b24633ee3fc52e79dcea9cb/image.png)  \n## 分析\n\n## 建议', 'state': 'opened', 'created_at': '2021-04-08T09:11:31.747+08:00', 'updated_at': '2021-04-15T11:24:15.587+08:00', 'closed_at': None, 'closed_by': None, 'labels': ['Done', '客户：中兴'], 'milestone': None, 'assignees': [], 'author': {'id': 48, 'name': '缪鹏程', 'username': 'miaopengcheng', 'state': 'active', 'avatar_url': 'https://secure.gravatar.com/avatar/b81be22b329a52c083dcb2ce610f312d?s=80&d=identicon', 'web_url': 'https://gitlab.skybilityha.com/miaopengcheng'}, 'assignee': None, 'user_notes_count': 3, 'merge_requests_count': 0, 'upvotes': 0, 'downvotes': 0, 'due_date': None, 'confidential': False, 'discussion_locked': None, 'web_url': 'https://gitlab.skybilityha.com/support/HA2.8/-/issues/787', 'time_stats': {'time_estimate': 0, 'total_time_spent': 0, 'human_time_estimate': None, 'human_total_time_spent': None}, 'task_completion_status': {'count': 0, 'completed_count': 0}, 'has_tasks': False, '_links': {'self': 'https://gitlab.skybilityha.com/api/v4/projects/45/issues/787', 'notes': 'https://gitlab.skybilityha.com/api/v4/projects/45/issues/787/notes', 'award_emoji': 'https://gitlab.skybilityha.com/api/v4/projects/45/issues/787/award_emoji', 'project': 'https://gitlab.skybilityha.com/api/v4/projects/45'}, 'references': {'short': '#787', 'relative': '#787', 'full': 'support/HA2.8#787'}, 'moved_to_id': None} [DataCollect.py:48:do_collect]
2021-07-19 09:44:14,841 [sky_gitlab_robot]: <ERROR> {'id': 3939, 'iid': 786, 'project_id': 45, 'title': '你好，我们有一套skybility双机发生故障，需排查原因，请分析，谢谢！', 'description': '## 问题来源\n\n* 客户: 中兴\n* 联系人: 胡文伟\n* 联系方式: hu.wenfei@zte.com.cn\n* 邮件日期：2021年4月7日(星期三)\n\n@jamesl @yangyingfa  @hblinux007 @fangjinzhen @husongtao\n\n## 问题描述\n你好，我们有一套skybility双机发生故障，需排查原因，请分析，谢谢！  \n[halog-icm-20210406T182522.tar.gz](/uploads/43719152197d0418463b3a73882cb47b/halog-icm-20210406T182522.tar.gz)  \n[halog-standby1-20210406T182633.tar.gz](/uploads/3cbd1852c9d8078e014b0e1261039f1c/halog-standby1-20210406T182633.tar.gz)  \n## 分析\n\n## 建议', 'state': 'opened', 'created_at': '2021-04-07T16:52:51.699+08:00', 'updated_at': '2021-04-15T11:24:06.611+08:00', 'closed_at': None, 'closed_by': None, 'labels': ['Done', '客户：中兴'], 'milestone': None, 'assignees': [], 'author': {'id': 48, 'name': '缪鹏程', 'username': 'miaopengcheng', 'state': 'active', 'avatar_url': 'https://secure.gravatar.com/avatar/b81be22b329a52c083dcb2ce610f312d?s=80&d=identicon', 'web_url': 'https://gitlab.skybilityha.com/miaopengcheng'}, 'assignee': None, 'user_notes_count': 2, 'merge_requests_count': 0, 'upvotes': 0, 'downvotes': 0, 'due_date': None, 'confidential': False, 'discussion_locked': None, 'web_url': 'https://gitlab.skybilityha.com/support/HA2.8/-/issues/786', 'time_stats': {'time_estimate': 0, 'total_time_spent': 0, 'human_time_estimate': None, 'human_total_time_spent': None}, 'task_completion_status': {'count': 0, 'completed_count': 0}, 'has_tasks': False, '_links': {'self': 'https://gitlab.skybilityha.com/api/v4/projects/45/issues/786', 'notes': 'https://gitlab.skybilityha.com/api/v4/projects/45/issues/786/notes', 'award_emoji': 'https://gitlab.skybilityha.com/api/v4/projects/45/issues/786/award_emoji', 'project': 'https://gitlab.skybilityha.com/api/v4/projects/45'}, 'references': {'short': '#786', 'relative': '#786', 'full': 'support/HA2.8#786'}, 'moved_to_id': None} [DataCollect.py:48:do_collect]
2021-07-19 09:44:14,927 [sky_gitlab_robot]: <ERROR> {'id': 3932, 'iid': 785, 'project_id': 45, 'title': '重庆中兴的CGSL系统上ha2.8部署支持', 'description': '## 问题来源\n\n* 客户: 中兴重庆分部\n* 联系人: 叶在伟  \n* 联系方式: 电话15696171575  \n* 邮件日期：\n\n@yangyingfa @hblinux007 @fangjinzhen @husongtao  \n\n## 问题描述\n客户在CGSL操作系统上部署ha2.8，部署遇到问题，请求支持。  \n\n## 分析\n\n## 建议', 'state': 'opened', 'created_at': '2021-04-06T13:56:23.923+08:00', 'updated_at': '2021-04-15T11:23:38.380+08:00', 'closed_at': None, 'closed_by': None, 'labels': ['Done', '客户：中兴'], 'milestone': None, 'assignees': [], 'author': {'id': 48, 'name': '缪鹏程', 'username': 'miaopengcheng', 'state': 'active', 'avatar_url': 'https://secure.gravatar.com/avatar/b81be22b329a52c083dcb2ce610f312d?s=80&d=identicon', 'web_url': 'https://gitlab.skybilityha.com/miaopengcheng'}, 'assignee': None, 'user_notes_count': 1, 'merge_requests_count': 0, 'upvotes': 0, 'downvotes': 0, 'due_date': None, 'confidential': False, 'discussion_locked': None, 'web_url': 'https://gitlab.skybilityha.com/support/HA2.8/-/issues/785', 'time_stats': {'time_estimate': 0, 'total_time_spent': 0, 'human_time_estimate': None, 'human_total_time_spent': None}, 'task_completion_status': {'count': 0, 'completed_count': 0}, 'has_tasks': False, '_links': {'self': 'https://gitlab.skybilityha.com/api/v4/projects/45/issues/785', 'notes': 'https://gitlab.skybilityha.com/api/v4/projects/45/issues/785/notes', 'award_emoji': 'https://gitlab.skybilityha.com/api/v4/projects/45/issues/785/award_emoji', 'project': 'https://gitlab.skybilityha.com/api/v4/projects/45'}, 'references': {'short': '#785', 'relative': '#785', 'full': 'support/HA2.8#785'}, 'moved_to_id': None} [DataCollect.py:48:do_collect]
2021-07-19 09:44:15,006 [sky_gitlab_robot]: <ERROR> {'id': 3923, 'iid': 782, 'project_id': 45, 'title': '新疆移动TDD网管刀片资源反复切换至备机问题，需配合处理，感谢！', 'description': '## 问题来源\n\n* 客户: zte\n* 联系人: 陈文海\n* 联系方式: 13669967820@163.com\n* 邮件日期：\n\n@jamesl @hblinux007 @fangjinzhen @husongtao\n\n## 问题描述\n故障现象：EMS网管ems2、zdc1刀片资源反复切换至备机，互相抢占资源\n\n现场操作：\n\n1、更换ZDC1网卡、内存条、主板、CPU，阵列卡；\n\n2、更换ems2主板，内存条；\n\n[halog-zdc1-20210326T093304.tar.gz](/uploads/be0a367fd18d92b221f18761c8e22bcc/halog-zdc1-20210326T093304.tar.gz)\n\n[halog-ems2-20210326T161932.tar.gz](/uploads/6d5bcee44da74343625c595b013a20a5/halog-ems2-20210326T161932.tar.gz)\n## 分析\n\n## 建议', 'state': 'opened', 'created_at': '2021-03-26T17:28:46.874+08:00', 'updated_at': '2021-04-02T09:33:26.369+08:00', 'closed_at': None, 'closed_by': None, 'labels': ['Done', '客户：中兴'], 'milestone': None, 'assignees': [{'id': 48, 'name': '缪鹏程', 'username': 'miaopengcheng', 'state': 'active', 'avatar_url': 'https://secure.gravatar.com/avatar/b81be22b329a52c083dcb2ce610f312d?s=80&d=identicon', 'web_url': 'https://gitlab.skybilityha.com/miaopengcheng'}], 'author': {'id': 14, 'name': 'yangyingfa', 'username': 'yangyingfa', 'state': 'active', 'avatar_url': 'https://gitlab.skybilityha.com/uploads/-/system/user/avatar/14/avatar.png', 'web_url': 'https://gitlab.skybilityha.com/yangyingfa'}, 'assignee': {'id': 48, 'name': '缪鹏程', 'username': 'miaopengcheng', 'state': 'active', 'avatar_url': 'https://secure.gravatar.com/avatar/b81be22b329a52c083dcb2ce610f312d?s=80&d=identicon', 'web_url': 'https://gitlab.skybilityha.com/miaopengcheng'}, 'user_notes_count': 1, 'merge_requests_count': 0, 'upvotes': 0, 'downvotes': 0, 'due_date': None, 'confidential': False, 'discussion_locked': None, 'web_url': 'https://gitlab.skybilityha.com/support/HA2.8/-/issues/782', 'time_stats': {'time_estimate': 0, 'total_time_spent': 0, 'human_time_estimate': None, 'human_total_time_spent': None}, 'task_completion_status': {'count': 0, 'completed_count': 0}, 'has_tasks': False, '_links': {'self': 'https://gitlab.skybilityha.com/api/v4/projects/45/issues/782', 'notes': 'https://gitlab.skybilityha.com/api/v4/projects/45/issues/782/notes', 'award_emoji': 'https://gitlab.skybilityha.com/api/v4/projects/45/issues/782/award_emoji', 'project': 'https://gitlab.skybilityha.com/api/v4/projects/45'}, 'references': {'short': '#782', 'relative': '#782', 'full': 'support/HA2.8#782'}, 'moved_to_id': None} [DataCollect.py:48:do_collect]
2021-07-19 09:44:15,145 [sky_gitlab_robot]: <ERROR> {'id': 3915, 'iid': 781, 'project_id': 45, 'title': '您好，求教双机web端的密码输错三次怎么解锁？', 'description': '## 问题来源\n\n* 客户: 浙江省邮电工程建设有限公司网络技术公司\n* 联系人:yechongyanghzb@126.com \n* 联系方式:yechongyanghzb@126.com \n* 邮件日期：2021年3月23日\n\n@jamesl @yangyingfa   @fangjinzhen @husongtao\n\n## 问题描述\n\n您好，求教双机web端的密码输错三次怎么解锁？\n\n## 分析\n\n## 建议', 'state': 'opened', 'created_at': '2021-03-23T13:48:18.977+08:00', 'updated_at': '2021-04-19T09:03:56.092+08:00', 'closed_at': None, 'closed_by': None, 'labels': ['Done', '客户：中兴'], 'milestone': None, 'assignees': [], 'author': {'id': 46, 'name': '尹咏玲', 'username': 'yinyongling', 'state': 'active', 'avatar_url': 'https://secure.gravatar.com/avatar/31c05dab4c0790cdbfdf92c5f2a007bd?s=80&d=identicon', 'web_url': 'https://gitlab.skybilityha.com/yinyongling'}, 'assignee': None, 'user_notes_count': 1, 'merge_requests_count': 0, 'upvotes': 0, 'downvotes': 0, 'due_date': None, 'confidential': False, 'discussion_locked': None, 'web_url': 'https://gitlab.skybilityha.com/support/HA2.8/-/issues/781', 'time_stats': {'time_estimate': 0, 'total_time_spent': 0, 'human_time_estimate': None, 'human_total_time_spent': None}, 'task_completion_status': {'count': 0, 'completed_count': 0}, 'has_tasks': False, '_links': {'self': 'https://gitlab.skybilityha.com/api/v4/projects/45/issues/781', 'notes': 'https://gitlab.skybilityha.com/api/v4/projects/45/issues/781/notes', 'award_emoji': 'https://gitlab.skybilityha.com/api/v4/projects/45/issues/781/award_emoji', 'project': 'https://gitlab.skybilityha.com/api/v4/projects/45'}, 'references': {'short': '#781', 'relative': '#781', 'full': 'support/HA2.8#781'}, 'moved_to_id': None} [DataCollect.py:48:do_collect]
2021-07-19 09:44:15,202 [sky_gitlab_robot]: <INFO> ############################################################ [DataCollect.py:56:do_collect]
2021-07-19 09:44:15,202 [sky_gitlab_robot]: <INFO> Ha28处理的issue单： [DataCollect.py:57:do_collect]
2021-07-19 09:44:15,202 [sky_gitlab_robot]: <INFO> 823, 818, 817, 813, 812, 811, 809, 805, 796, 793, 789, 787, 786, 785, 782, 781 [DataCollect.py:58:do_collect]
2021-07-19 09:44:15,203 [sky_gitlab_robot]: <INFO> ############################################################ [DataCollect.py:59:do_collect]
2021-07-19 09:44:15,238 [sky_gitlab_robot]: <INFO> Write new data to XlsBot/log/ha2.8_zte.xlsx [ExcelActor.py:215:write_new_file]
2021-07-19 09:44:16,504 [sky_gitlab_robot]: <INFO> close issue 823 success [DataCollect.py:75:close_recorded_issue]
2021-07-19 09:44:17,350 [sky_gitlab_robot]: <INFO> close issue 818 success [DataCollect.py:75:close_recorded_issue]
2021-07-19 09:44:18,001 [sky_gitlab_robot]: <INFO> close issue 817 success [DataCollect.py:75:close_recorded_issue]
2021-07-19 09:44:18,725 [sky_gitlab_robot]: <INFO> close issue 813 success [DataCollect.py:75:close_recorded_issue]
2021-07-19 09:44:19,524 [sky_gitlab_robot]: <INFO> close issue 812 success [DataCollect.py:75:close_recorded_issue]
2021-07-19 09:44:20,277 [sky_gitlab_robot]: <INFO> close issue 811 success [DataCollect.py:75:close_recorded_issue]
2021-07-19 09:44:20,935 [sky_gitlab_robot]: <INFO> close issue 809 success [DataCollect.py:75:close_recorded_issue]
2021-07-19 09:44:21,461 [sky_gitlab_robot]: <INFO> close issue 805 success [DataCollect.py:75:close_recorded_issue]
2021-07-19 09:44:21,965 [sky_gitlab_robot]: <INFO> close issue 796 success [DataCollect.py:75:close_recorded_issue]
2021-07-19 09:44:22,406 [sky_gitlab_robot]: <INFO> close issue 793 success [DataCollect.py:75:close_recorded_issue]
2021-07-19 09:44:23,822 [sky_gitlab_robot]: <INFO> close issue 789 success [DataCollect.py:75:close_recorded_issue]
2021-07-19 09:44:24,607 [sky_gitlab_robot]: <INFO> close issue 787 success [DataCollect.py:75:close_recorded_issue]
2021-07-19 09:44:25,344 [sky_gitlab_robot]: <INFO> close issue 786 success [DataCollect.py:75:close_recorded_issue]
2021-07-19 09:44:25,852 [sky_gitlab_robot]: <INFO> close issue 785 success [DataCollect.py:75:close_recorded_issue]
2021-07-19 09:44:26,732 [sky_gitlab_robot]: <INFO> close issue 782 success [DataCollect.py:75:close_recorded_issue]
2021-07-19 09:44:27,211 [sky_gitlab_robot]: <INFO> close issue 781 success [DataCollect.py:75:close_recorded_issue]
2021-07-19 09:44:27,639 [sky_gitlab_robot]: <INFO> ############################################################ [DataCollect.py:56:do_collect]
2021-07-19 09:44:27,640 [sky_gitlab_robot]: <INFO> Ha28处理的issue单： [DataCollect.py:57:do_collect]
2021-07-19 09:44:27,640 [sky_gitlab_robot]: <INFO>  [DataCollect.py:58:do_collect]
2021-07-19 09:44:27,640 [sky_gitlab_robot]: <INFO> ############################################################ [DataCollect.py:59:do_collect]
2021-07-19 09:44:27,654 [sky_gitlab_robot]: <INFO> Write new data to XlsBot/log/ha2.8_abc.xlsx [ExcelActor.py:215:write_new_file]
2021-07-19 01:48:23,241 [yangyingfa]: <ERROR> {'id': 4163, 'iid': 824, 'project_id': 45, 'title': '麻烦傲冠同事帮忙确认下数据库切不备机的原因，感谢', 'description': '## 问题来源\n\n* 客户: \n* 联系人: sheng.chunming1@zte.com.cn\n* 联系方式: \n* 邮件日期：\n\n@miaopengcheng @hblinux007 @xuyunfeng \n\n## 问题描述\n\n## 分析\n\n## 建议', 'state': 'opened', 'created_at': '2021-07-19T09:46:19.194+08:00', 'updated_at': '2021-07-19T09:47:08.649+08:00', 'closed_at': None, 'closed_by': None, 'labels': ['Done', '客户：中兴'], 'milestone': None, 'assignees': [{'id': 14, 'name': 'yangyingfa', 'username': 'yangyingfa', 'state': 'active', 'avatar_url': 'https://gitlab.skybilityha.com/uploads/-/system/user/avatar/14/avatar.png', 'web_url': 'https://gitlab.skybilityha.com/yangyingfa'}], 'author': {'id': 14, 'name': 'yangyingfa', 'username': 'yangyingfa', 'state': 'active', 'avatar_url': 'https://gitlab.skybilityha.com/uploads/-/system/user/avatar/14/avatar.png', 'web_url': 'https://gitlab.skybilityha.com/yangyingfa'}, 'assignee': {'id': 14, 'name': 'yangyingfa', 'username': 'yangyingfa', 'state': 'active', 'avatar_url': 'https://gitlab.skybilityha.com/uploads/-/system/user/avatar/14/avatar.png', 'web_url': 'https://gitlab.skybilityha.com/yangyingfa'}, 'user_notes_count': 1, 'merge_requests_count': 0, 'upvotes': 0, 'downvotes': 0, 'due_date': None, 'confidential': False, 'discussion_locked': None, 'web_url': 'https://gitlab.skybilityha.com/support/HA2.8/-/issues/824', 'time_stats': {'time_estimate': 0, 'total_time_spent': 0, 'human_time_estimate': None, 'human_total_time_spent': None}, 'task_completion_status': {'count': 0, 'completed_count': 0}, 'has_tasks': False, '_links': {'self': 'https://gitlab.skybilityha.com/api/v4/projects/45/issues/824', 'notes': 'https://gitlab.skybilityha.com/api/v4/projects/45/issues/824/notes', 'award_emoji': 'https://gitlab.skybilityha.com/api/v4/projects/45/issues/824/award_emoji', 'project': 'https://gitlab.skybilityha.com/api/v4/projects/45'}, 'references': {'short': '#824', 'relative': '#824', 'full': 'support/HA2.8#824'}, 'moved_to_id': None} [DataCollect.py:48:do_collect]
2021-07-19 01:48:23,323 [yangyingfa]: <INFO> ############################################################ [DataCollect.py:56:do_collect]
2021-07-19 01:48:23,323 [yangyingfa]: <INFO> Ha28处理的issue单： [DataCollect.py:57:do_collect]
2021-07-19 01:48:23,324 [yangyingfa]: <INFO> 824 [DataCollect.py:58:do_collect]
2021-07-19 01:48:23,324 [yangyingfa]: <INFO> ############################################################ [DataCollect.py:59:do_collect]
2021-07-19 01:48:23,388 [yangyingfa]: <INFO> Backup xls file XlsBot/log/ha2.8_zte.xlsx to XlsBot/log/ha2.8_zte.bak.xlsx [ExcelActor.py:211:back_old_file]
2021-07-19 01:48:23,388 [yangyingfa]: <INFO> Write new data to XlsBot/log/ha2.8_zte.xlsx [ExcelActor.py:215:write_new_file]
2021-07-19 01:48:23,893 [yangyingfa]: <INFO> close issue 824 success [DataCollect.py:75:close_recorded_issue]
2021-07-19 01:48:24,246 [yangyingfa]: <INFO> ############################################################ [DataCollect.py:56:do_collect]
2021-07-19 01:48:24,247 [yangyingfa]: <INFO> Ha28处理的issue单： [DataCollect.py:57:do_collect]
2021-07-19 01:48:24,247 [yangyingfa]: <INFO>  [DataCollect.py:58:do_collect]
2021-07-19 01:48:24,247 [yangyingfa]: <INFO> ############################################################ [DataCollect.py:59:do_collect]
2021-07-19 01:48:24,280 [yangyingfa]: <INFO> Backup xls file XlsBot/log/ha2.8_abc.xlsx to XlsBot/log/ha2.8_abc.bak.xlsx [ExcelActor.py:211:back_old_file]
2021-07-19 01:48:24,281 [yangyingfa]: <INFO> Write new data to XlsBot/log/ha2.8_abc.xlsx [ExcelActor.py:215:write_new_file]
